# H2 Embedded Database - Recommended for Group Development
spring.datasource.url=jdbc:h2:mem:smartcampus_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (Very useful for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8081

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.lk.sliit=DEBUG